ALTER TABLE T_SOS_APP_USER ADD (NOME_EXIBICAO VARCHAR2(100 CHAR));
ALTER TABLE T_SOS_APP_USER ADD (DDD VARCHAR2(2 CHAR));
ALTER TABLE T_SOS_APP_USER ADD (NUMERO_LOCAL VARCHAR2(9 CHAR));

UPDATE T_SOS_APP_USER SET NOME_EXIBICAO = 'Administrador', DDD = '11', NUMERO_LOCAL = '999000001' WHERE USERNAME = 'admin';
UPDATE T_SOS_APP_USER SET NOME_EXIBICAO = 'Cidadão', DDD = '11', NUMERO_LOCAL = '999000002' WHERE USERNAME = 'citizen';
