ALTER TABLE T_SOS_APP_USER ADD (LOCALIZACAO VARCHAR2(200 CHAR));

UPDATE T_SOS_APP_USER
SET LOCALIZACAO = 'Avenida Paulista 1000, Sao Paulo'
WHERE USERNAME = 'admin';

UPDATE T_SOS_APP_USER
SET LOCALIZACAO = 'Rua ABC 123, Sao Paulo'
WHERE USERNAME = 'citizen';
