spring:
  application:
    name: sos-localiza
  
  profiles:
    active: oracle-fiap
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

# Configurações do Twilio - Removido (usando simulação local)
# twilio:
#   account-sid: ${TWILIO_ACCOUNT_SID:ACb84a1c0afbb6628678209002a9db4d6c}
#   auth-token: ${TWILIO_AUTH_TOKEN:7a420445aa2fc29161ac7cc22e2b8353}
#   trial-number: ${TWILIO_TRIAL_NUMBER:+15005550006}

# Configurações do Swagger/OpenAPI - Temporariamente desabilitado
# springdoc:
#   api-docs:
#     path: /api-docs
#   swagger-ui:
#     path: /swagger-ui.html
#     operationsSorter: method
#     tagsSorter: alpha
#     tryItOutEnabled: true

---
spring:
  config:
    activate:
      on-profile: oracle
  
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${ORACLE_USERNAME:soslocaliza}
    password: ${ORACLE_PASSWORD:password}
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
