spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    open-in-view: false

# Configurações do Twilio para desenvolvimento
twilio:
  account-sid: ${TWILIO_ACCOUNT_SID:your_account_sid}
  auth-token: ${TWILIO_AUTH_TOKEN:your_auth_token}
  trial-number: ${TWILIO_TRIAL_NUMBER:your_trial_number}

# Configurações do servidor
server:
  port: 8080
  servlet:
    context-path: /api

# Configurações de logging para desenvolvimento
logging:
  level:
    com.example.SosLocaliza: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.twilio: DEBUG
