ALTER TABLE T_SOS_APP_USER ADD COLUMN NOME_EXIBICAO VARCHAR(100);
ALTER TABLE T_SOS_APP_USER ADD COLUMN DDD VARCHAR(2);
ALTER TABLE T_SOS_APP_USER ADD COLUMN NUMERO_LOCAL VARCHAR(9);

UPDATE T_SOS_APP_USER SET NOME_EXIBICAO = 'Administrador', DDD = '11', NUMERO_LOCAL = '999000001' WHERE USERNAME = 'admin';
UPDATE T_SOS_APP_USER SET NOME_EXIBICAO = 'Cidadão', DDD = '11', NUMERO_LOCAL = '999000002' WHERE USERNAME = 'citizen';
