ALTER TABLE T_SOS_APP_USER ADD COLUMN LOCALIZACAO VARCHAR(200);

UPDATE T_SOS_APP_USER
SET LOCALIZACAO = 'Avenida Paulista 1000, Sao Paulo'
WHERE USERNAME = 'admin';

UPDATE T_SOS_APP_USER
SET LOCALIZACAO = 'Rua ABC 123, Sao Paulo'
WHERE USERNAME = 'citizen';
